version: "3"

services:
  sql:
    build: ./sql
    platform: linux/x86_64
    volumes:
      - tweeter:/var/lib/mysql
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
#  app:
#    build: frontend
#    depends_on:
#      - node
##    For deploying to server use ports: - 80:80
#    ports:
#      - 80:80
  node:
    build: backend
    platform: linux/x86_64
    env_file:
      - .env
    ports:
      - 8080:4200
    user: "node"
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
volumes:
  tweeter: